# Generated by Django 4.0.6 on 2022-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(max_length=100, verbose_name='Наименование на русском')),
                ('title_original', models.CharField(blank=True, max_length=100, verbose_name='Наименование на языке оригинала')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('authors', models.CharField(max_length=255, verbose_name='Автор(ы)')),
                ('cover_photo', models.ImageField(upload_to='media/photo/%Y/%m/%d/', verbose_name='Фото обложки')),
                ('author_photo_1', models.ImageField(blank=True, upload_to='media/photo/%Y/%m/%d/', verbose_name='Фото автора')),
                ('author_photo_2', models.ImageField(blank=True, upload_to='media/photo/%Y/%m/%d/', verbose_name='Фото автора')),
                ('author_photo_3', models.ImageField(blank=True, upload_to='media/photo/%Y/%m/%d/', verbose_name='Фото автора')),
                ('author_photo_4', models.ImageField(blank=True, upload_to='media/photo/%Y/%m/%d/', verbose_name='Фото автора')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена за день пользования')),
                ('publication_date', models.PositiveIntegerField(verbose_name='Год издания')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('num_of_pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий о состоянии')),
                ('in_order', models.BooleanField(default=False, verbose_name='В заказе')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
