# Generated by Django 4.0.6 on 2022-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
