# Generated by Django 4.0.6 on 2022-08-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
