# Generated by Django 4.0.6 on 2022-08-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('agreement', models.BooleanField(default=True, verbose_name='Пользовательское соглашение')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('book', models.ManyToManyField(to='books.book')),
            ],
        ),
    ]
