# Generated by Django 4.0.6 on 2022-08-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_slug'),
        ('clients', '0001_initial'),
        ('library_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.AddField(
            model_name='order',
            name='book1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_1', to='books.book', verbose_name='Книга 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_2', to='books.book', verbose_name='Книга 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book3',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_3', to='books.book', verbose_name='Книга 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book4',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_4', to='books.book', verbose_name='Книга 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book5',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_5', to='books.book', verbose_name='Книга 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='clients.client'),
        ),
    ]
