# Generated by Django 4.0.6 on 2022-08-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_slug'),
        ('library_managment', '0002_alter_order_options_remove_order_book_order_book1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_2', to='books.book', verbose_name='Книга 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_3', to='books.book', verbose_name='Книга 3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_4', to='books.book', verbose_name='Книга 4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_5', to='books.book', verbose_name='Книга 5'),
        ),
    ]
